name: New Version

on:
  workflow_run:
    workflows:
      - Build and Test
    types:
      - completed
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: "The level of the version bump"
        required: true
        default: "minor"
        options:
          - "major"
          - "minor"
          - "patch"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ github.event.inputs.level || 'minor' }}

      - name: Delete existing tag if it exists
        run: |
          git tag -d ${{ steps.bump-semver.outputs.new_version }} 2>/dev/null || true
          git push --delete origin ${{ steps.bump-semver.outputs.new_version }} 2>/dev/null || true
        continue-on-error: true

      - name: Create and push new tag
        run: |
          git tag ${{ steps.bump-semver.outputs.new_version }} -m "${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}"
          git push origin ${{ steps.bump-semver.outputs.new_version }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
